### ISSUE TITLE
Generating a random number while scanning barcode

### ISSUE THREAD

**Issue by lakshman2891** [mhadaily/ng2-barcode-validator#2]
Hey @mhadaily! thank you for documenting everything. this is very helpful.
I am new to typescript and i integrated quagga successfully. the only issue now is the generated number after scanning is completely different from actual bar code. and when i take a close look even it is doing same in the GIF. please do let me know what to do next.

**Comment by mhadaily** [comment]
Hey @lakshman2891 
I am glad that it helps you. However, quagga is generating and reading the barcodes and I think you should somehow open an issue on their repository. Angular itself doesn't do anything in this application. 

As a suggestion, it would be helpful if you can upgrade your quagga to the latest version. I assume there must be a newer version as this repo is pretty old and I am not updating it frequently.  

Please let me know if I can help more.

**Comment by lakshman2891** [comment]
hello @mhadaily !
thank you for the input.
1. yes i am using the most updated repo of quagga.
2. the issue raised already. i am attaching the link of the issue here.
https://github.com/serratus/quaggaJS/issues/219. on September 4 and it is unanswered.

there are few suggestions like use only one type of bar code. but it is of no use to have only a single type.

Should i rise the separate issue or tag the owner in the same issue?

**Comment by mhadaily** [comment]
Yeah, you definitely open a new issue and maybe other people have the same issue and they can see and reply. 

BTW, having a single barcode type is a good idea, I had kinda same issue and I resolve with a better HD webcam and single type.

**Comment by lakshman2891** [comment]
sure, i will do it. thank you @mhadaily
