### ISSUE TITLE
No licence specified for library

### ISSUE THREAD

**Issue by joshilewis** [mhadaily/ng2-barcode-validator#4]
Hi, I would like to re-use some of the code in this library (`BarcodeDecoderService`) but there is no licence specified for the project. Please advise me on how I should proceed.

**Comment by mhadaily** [comment]
Hi @joshilewis, Just added MIT License, feel free to use whatever you like the code.

**Comment by joshilewis** [comment]
Thanks! And thanks again for a great library :)
