### ISSUE TITLE
Reads barcode only once

### ISSUE THREAD

**Issue by sebscape** [mhadaily/ng2-barcode-validator#5]
(Thank you for this library)

I am attempting to integrate your code into my own application. I am facing an issue which I have reproduced on your demo page:
1. hold up barcode-1 to camera -> Success: beeps; my code is displayed with error that it could not be found (as I believe is expected)
2. hold up barcode-2 to camera -> Fail: framer finds barcode; no beep, no updates.
3. hold up barcode-1 to camera -> Fail: framer finds barcode; no beep, no updates.

- I have reproduced the error making sure all my barcodes use the same format (128-B and i2of5).

Does something need to get reset after each read?

**Comment by mhadaily** [comment]
Hi, 
Just upgraded to angular 5 and updated all deps, should be fine now. 

Thanks,
