### ISSUE TITLE
Don't work webcam

### ISSUE THREAD

**Issue by 9marta5** [mhadaily/ng2-barcode-validator#9]
Hi, in your live example my webcam start correctly. I copy, install and start the project but the webcam doesn't start. I use the last version of chrome.
I forgot something?

Thank you.

**Comment by mhadaily** [comment]
Hi, 
Can you check your console and see if there is any error? it's much better if you can also reproduce it in another repo and I can have a look at your project ?

Thanks,

**Comment by 9marta5** [comment]
Hi,
I've solve. The problem was on the configuration of the permission of chrome at the url of my project. I had denied the webcam. Now it's work. 
Thank you very much for the support.

**Comment by mhadaily** [comment]
@9marta5 thanks for letting me know
